defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
    exclude:
      ['generate_ranking', 'LICENSE', 'README.md']
    timezone: "Europe/Amsterdam"

timezone: Europe/Amsterdam
