on:

  workflow_dispatch:

jobs:
  get_calendar:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3.3.0

      - name: set user
        run: |
          git config --global user.email "wb@retta.nl"
          git config --global user.name "wijnandb"

      - name: pull latest changes
        run: git pull

      - name: install dependencies
        run: pip install requests bs4 unidecode

      - name: run calendar_scraper
        run: python generate_ranking/calendar_update.py

      - name: check for changes
        id: git-check
        run: |
          git diff --quiet || (git add . && git commit -m "Calendar scraped at $(date +'%Y-%m-%dT%H:%M:%S')" && git push origin HEAD:main)
