on:
  # schedule:
  #  - cron: '5 2,16 * * *'

  workflow_dispatch:

jobs:
  scrape-startlist:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3.3.0

      - name: set user
        run: |
          git config --global user.email "wb@retta.nl"
          git config --global user.name "wijnandb"

      - name: pull latest changes
        run: git pull

      - name: install dependencies
        run: pip install requests bs4 unidecode

      - name: run startlist scraper
        run: python generate_ranking/current_races.py

      - name: Check for new data
        id: check-new-data
        run: |
          git diff --quiet || (git add . && git commit -m "New startlist scraped at $(date +'%Y-%m-%dT%H:%M:%S')" && git push origin HEAD:main)
